In [1]:
import numpy as np
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [2]:
a= np.array([[5,5,5,],[5,5,5],[5,5,5]])
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [3]:
type(a)

numpy.ndarray

In [4]:
a[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [5]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [6]:
c=np.zeros(3)
c

array([0., 0., 0.])

In [7]:
d=np.ones(2)
d

array([1., 1.])

In [8]:
f=np.empty(3)
f

array([0., 0., 0.])

In [9]:
g=np.arange(2,20)
g

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [10]:
h=np.arange(2,20,2)
h

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
i=np.linspace(0,10,num=5)
i

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
j=np.zeros((2,3))
j

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
k=np.empty((3,3))
k

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.45050994e-321],
       [5.04620501e+180, 2.39800679e-258, 6.01347002e-154]])

In [14]:
#making and reshaping 3D array
l=np.arange(24).reshape(2,3,4)
l

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# numpy practice session

In [15]:
#import the library in jupiter notebook
import numpy as np

# Creating an array using numpy

In [16]:
food=np.array(["pakpora","samosa","Raita"])
food

array(['pakpora', 'samosa', 'Raita'], dtype='<U7')

In [17]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [18]:
len(food)

3

In [19]:
price[2]

5

In [20]:
#zeeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
# for a range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# specify a range
np.arange(2,20,2.5)

array([ 2. ,  4.5,  7. ,  9.5, 12. , 14.5, 17. , 19.5])

In [24]:
np.arange(36).reshape(3,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [25]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [26]:
#specify your data type
np.ones(5,dtype=np.int64) #in the place of int we can write float

array([1, 1, 1, 1, 1], dtype=int64)

# Array functions

In [27]:
a=np.array([10,22,0.03, 0.33,21,100,101,99.99])
a

array([1.000e+01, 2.200e+01, 3.000e-02, 3.300e-01, 2.100e+01, 1.000e+02,
       1.010e+02, 9.999e+01])

In [28]:
a.sort()
a

array([3.000e-02, 3.300e-01, 1.000e+01, 2.100e+01, 2.200e+01, 9.999e+01,
       1.000e+02, 1.010e+02])

In [29]:
b=np.array([2,3,1.3,3.1,22,43,121])
b

array([  2. ,   3. ,   1.3,   3.1,  22. ,  43. , 121. ])

In [30]:
c=np.concatenate((a,b))
c

array([3.000e-02, 3.300e-01, 1.000e+01, 2.100e+01, 2.200e+01, 9.999e+01,
       1.000e+02, 1.010e+02, 2.000e+00, 3.000e+00, 1.300e+00, 3.100e+00,
       2.200e+01, 4.300e+01, 1.210e+02])

In [31]:
c.sort()
c

array([3.000e-02, 3.300e-01, 1.300e+00, 2.000e+00, 3.000e+00, 3.100e+00,
       1.000e+01, 2.100e+01, 2.200e+01, 2.200e+01, 4.300e+01, 9.999e+01,
       1.000e+02, 1.010e+02, 1.210e+02])

# 2-D Array

In [32]:
a=np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [33]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [35]:
a=np.array([[[0,1,2,3],[4,5,6,7]],[[3,2,1,5],[6,7,8,9]],[[1,4,6,8],[4,8,2,5]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[3, 2, 1, 5],
        [6, 7, 8, 9]],

       [[1, 4, 6, 8],
        [4, 8, 2, 5]]])

In [36]:
#to find the number of dimensions
a.ndim

3

In [37]:
#shape
a.shape

(3, 2, 4)

In [38]:
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
#reshape
np.reshape(a,newshape=(1,9),order='c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [42]:
#convert 1D to 2D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a.shape

(9,)

In [45]:
b=a[np.newaxis,:]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [46]:
b.shape

(1, 9)

In [48]:
c=a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [49]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [51]:
a.mean()

5.0